[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flipper = "AaDDkYTbHCh5JogkpGAKnhFUdGEZoWiYkM9NNgVTo85W"
hello = "3FZusWeV9GBm8VT6FfmyEQmUAq4TtTMGz8eQAcLnUHxA"
solengage = "FMmxYCKBvwr3nQ66MxVYQLWt4CqN5wyvRWRBdQX1bZSN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
