[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solengage = "HtbFBjrFofeiVN3fhP8Urp1upxyRLHEVPcXRahJFtLgg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://supertea-solanan-66b1.devnet.rpcpool.com/d914275f-7a7d-491c-9f0e-61cb6466f39a"
wallet = "/Users/olivmath/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
