[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solengage = "2e3n681eydMY7t35bHD53eLfaifH3yQzQEsmgfhKV7E5"

[programs.devnet]
solengage = "2e3n681eydMY7t35bHD53eLfaifH3yQzQEsmgfhKV7E5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/olivmath/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
