[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
influnest = "DS6344gi387M4e6XvS99QQXGiDmY6qQi4xYxqGUjFbB3"

[programs.devnet]
influnest = "DS6344gi387M4e6XvS99QQXGiDmY6qQi4xYxqGUjFbB3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/olivmath/.config/solana/id.json"

[scripts]
test = "anchor deploy && yarn run ts-mocha -p ./tsconfig.json tests/**/*.ts"
